import {readFileSync,writeFileSync} from 'node:fs';
const dir='.scratch/diagnostico-commerce';
const read=t=>JSON.parse(readFileSync(`${dir}/${t}.json`));
const D=Object.fromEntries(Object.keys(read('manifest').tabelas).map(t=>[t,read(t)]));
const map=(a,k='id')=>new Map(a.map(r=>[r[k],r]));
const channels=map(D.canais),accounts=map(D.contas_canal),ads=map(D.anuncios),byCode=map(D.anuncios,'codigo_externo'),products=map(D.produtos,'sku');
const name=id=>{let a=accounts.get(id);return a?`${channels.get(a.canal_id)?.nome} | ${a.nome}`:id};
const n=v=>Number(v??0),sum=(a,k)=>a.reduce((s,r)=>s+n(r[k]),0),rr=x=>Math.round(x*100)/100;
function group(a,fn){const m=new Map();for(const r of a){const k=fn(r);m.set(k,[...(m.get(k)||[]),r]);}return m;}
const bounds=(a,k)=>{const v=a.map(r=>r[k]).filter(Boolean).sort();return [v[0]??null,v.at(-1)??null]};
const excluded=p=>D.exclusoes_analise.some(e=>p.data>=e.data_inicio&&p.data<=e.data_fim&&(!e.canal_id||e.canal_id===p.canal_id)&&(!e.conta_canal_id||e.conta_canal_id===p.conta_canal_id));
const P=D.pedidos.filter(p=>!excluded(p)),pm=map(P);
const items=D.pedido_itens.map(i=>{const p=pm.get(i.pedido_id);if(!p)return null;const a=ads.get(i.anuncio_id)||byCode.get(i.codigo_externo);return {...i,p,a,sku:i.sku||a?.sku_canal||i.codigo_externo};}).filter(Boolean);
const metrics=a=>({rows:a.length,orders:a.length,cancel:a.filter(p=>p.cancelado).length,gross:rr(sum(a,'total')),cancelValue:rr(sum(a.filter(p=>p.cancelado),'total')),net:rr(sum(a.filter(p=>!p.cancelado),'total')),ticket:rr(sum(a.filter(p=>!p.cancelado),'total')/a.filter(p=>!p.cancelado).length)});
const periods={jul:['2026-07-01','2026-07-31'],ago:['2026-08-01','2026-08-31'],ago21:['2026-08-01','2026-08-21'],set21:['2026-09-01','2026-09-21'],ago14:['2026-08-01','2026-08-14'],set14:['2026-09-01','2026-09-14'],w1:['2026-08-24','2026-08-30'],w2:['2026-08-31','2026-09-06'],w3:['2026-09-07','2026-09-13'],w4:['2026-09-14','2026-09-20']};
Object.assign(periods,{ago20:['2026-08-01','2026-08-20'],set20:['2026-09-01','2026-09-20'],prev14:['2026-08-24','2026-09-06'],last14:['2026-09-07','2026-09-20']});
const inPeriod=(r,[b,e])=>r.data>=b&&r.data<=e;
let summary={manifest:read('manifest'),coverage:{},accounts:[],exclusion:{rule:D.exclusoes_analise.map(({motivo,data_inicio,data_fim})=>({motivo,data_inicio,data_fim})),removed:metrics(D.pedidos.filter(excluded))}};
for(const [t,a]of Object.entries(D))summary.coverage[t]={rows:a.length,...Object.fromEntries(['data','inicio','fim','capturado_em','sincronizado_em','vigente_de','criado_em'].filter(k=>a.some(r=>r[k])).map(k=>[k,bounds(a,k)]))};
for(const a of D.contas_canal){const ps=P.filter(p=>p.conta_canal_id===a.id),vs=D.vendas_diarias.filter(v=>v.conta_canal_id===a.id&&!excluded(v)),as=D.anuncios.filter(x=>x.conta_canal_id===a.id);let out={id:a.id,name:name(a.id),reputacao:a.reputacao,reputacaoAtualizada:a.reputacao_atualizada_em,orderDates:bounds(ps,'data'),dailyDates:bounds(vs,'data'),catalogDate:bounds(as,'sincronizado_em'),orders:ps.length,ads:as.length,status:Object.fromEntries([...group(as,r=>r.status)].map(([k,v])=>[k,v.length])),periods:{}};
for(const[k,period]of Object.entries(periods)){const pp=ps.filter(p=>inPeriod(p,period)),vv=vs.filter(p=>inPeriod(p,period));out.periods[k]={...metrics(pp),diarias:{days:vv.length,gross:rr(sum(vv,'receita')),net:rr(sum(vv,'receita')-sum(vv,'valor_cancelado')),orders:sum(vv,'pedidos'),visits:sum(vv,'visitas'),ads:rr(sum(vv,'investimento_ads'))}};}
summary.accounts.push(out);}
summary.monthly=[...group(P,p=>p.data.slice(0,7)+'|'+name(p.conta_canal_id))].map(([k,a])=>({key:k,...metrics(a)})).sort((a,b)=>a.key.localeCompare(b.key));
summary.costs=Object.fromEntries(['custo_unitario','embalagem','aliquota_impostos','peso_kg'].map(k=>[k,D.produtos.filter(p=>p[k]!=null).length]));
summary.imports=D.importacoes.sort((a,b)=>b.criado_em.localeCompare(a.criado_em));
summary.adsPeriods=[...group(D.anuncio_ads,r=>r.inicio+'|'+r.fim+'|'+name(ads.get(r.anuncio_id)?.conta_canal_id))].map(([k,a])=>({key:k,rows:a.length,investment:rr(sum(a,'investimento')),revenue:rr(sum(a,'receita')),clicks:sum(a,'cliques'),impressions:sum(a,'impressoes'),direct:sum(a,'vendas_diretas'),indirect:sum(a,'vendas_indiretas')}));
summary.snapshot=[...group(D.anuncio_precos_vitrine,r=>r.capturado_em.slice(0,10)+'|'+name(ads.get(r.anuncio_id)?.conta_canal_id))].map(([k,a])=>({key:k,rows:a.length,zero:a.filter(x=>x.disponivel===0).length,positive:a.filter(x=>n(x.disponivel)>0).length}));
summary.dailyCoverage=[...group(D.anuncio_desempenho_diario,r=>name(ads.get(r.anuncio_id)?.conta_canal_id))].map(([k,a])=>({key:k,dates:bounds(a,'data'),days:new Set(a.map(r=>r.data)).size,rows:a.length,visits:sum(a,'visitas'),sales:sum(a,'vendas')}));
const latestStock=new Map();for(const x of D.anuncio_precos_vitrine){const cur=latestStock.get(x.anuncio_id);if(!cur||x.capturado_em>cur.capturado_em)latestStock.set(x.anuncio_id,x);}
summary.productAccounts=[];
for(const[k,aa]of group(items,i=>name(i.p.conta_canal_id)+'|'+i.sku)){const active=aa.filter(i=>!i.p.cancelado);if(!active.length)continue;let x={key:k,sku:aa[0].sku,title:aa[0].titulo,account:name(aa[0].p.conta_canal_id),periods:{}};for(const[per,range]of Object.entries(periods)){const ii=active.filter(i=>inPeriod(i.p,range));x.periods[per]={units:sum(ii,'quantidade'),revenue:rr(sum(ii,'total')),asp:rr(sum(ii,'total')/sum(ii,'quantidade'))};}const listings=D.anuncios.filter(a=>a.conta_canal_id===aa[0].p.conta_canal_id&&a.sku_canal===aa[0].sku);x.listings=listings.map(a=>({mlb:a.codigo_externo,status:a.status,price:a.preco_atual,asof:a.sincronizado_em,stock:latestStock.get(a.id)??null}));summary.productAccounts.push(x);}
summary.listingAccounts=[];
for(const[k,aa]of group(items.filter(i=>i.a),i=>i.a.id)){const a=aa[0].a;let x={mlb:a.codigo_externo,sku:a.sku_canal,title:a.titulo,account:name(a.conta_canal_id),type:a.tipo,status:a.status,price:a.preco_atual,asof:a.sincronizado_em,stock:latestStock.get(k)??null,periods:{}};for(const[per,range]of Object.entries(periods)){const ii=aa.filter(i=>!i.p.cancelado&&inPeriod(i.p,range));const vv=D.anuncio_desempenho_diario.filter(v=>v.anuncio_id===k&&inPeriod(v,range));x.periods[per]={units:sum(ii,'quantidade'),revenue:rr(sum(ii,'total')),asp:rr(sum(ii,'total')/sum(ii,'quantidade')),visits:sum(vv,'visitas'),visitDays:vv.length};}summary.listingAccounts.push(x);}
summary.feeCoverage=[...group(P.filter(p=>!p.cancelado&&p.data>='2026-08-01'),p=>name(p.conta_canal_id)+'|'+p.data.slice(0,7))].map(([k,a])=>({key:k,orders:a.length,revenue:rr(sum(a,'total')),feeOrders:a.filter(p=>p.comissao!=null).length,fee:rr(sum(a,'comissao')),shippingOrders:a.filter(p=>p.frete_vendedor!=null).length,shipping:rr(sum(a,'frete_vendedor')),interestOrders:a.filter(p=>p.juros!=null).length,interest:rr(sum(a,'juros')),sources:Object.fromEntries([...group(a,r=>r.comissao_origem)].map(([k,v])=>[k,v.length]))}));
summary.reconciliation=[];
for(const a of summary.accounts)for(const[k,range]of Object.entries(periods)){const ii=items.filter(i=>i.p.conta_canal_id===a.id&&!i.p.cancelado&&inPeriod(i.p,range));a.periods[k].itemNet=rr(sum(ii,'total'));a.periods[k].units=sum(ii,'quantidade');a.periods[k].itemOrders=new Set(ii.map(i=>i.pedido_id)).size;}
for(const [acc,a]of group(P,p=>p.conta_canal_id))for(const[month,pp]of group(a,p=>p.data.slice(0,7))){const dd=D.vendas_diarias.filter(d=>d.conta_canal_id===acc&&d.data.startsWith(month)&&!excluded(d));summary.reconciliation.push({account:name(acc),month,orderRevenue:rr(sum(pp,'total')),dailyRevenue:rr(sum(dd,'receita')),diff:rr(sum(dd,'receita')-sum(pp,'total')),orders:pp.length,dailyOrders:sum(dd,'pedidos')});}
writeFileSync(`${dir}/resumo.json`,JSON.stringify(summary,null,2));
console.log(JSON.stringify({...summary,productAccounts:summary.productAccounts.length,listingAccounts:summary.listingAccounts.length,imports:summary.imports.slice(0,10),monthly:undefined,reconciliation:summary.reconciliation.filter(x=>Math.abs(x.diff)>1),manifest:undefined,coverage:summary.coverage},null,2));
