import{readFileSync,writeFileSync}from'node:fs';
const d='.scratch/diagnostico-commerce',R=t=>JSON.parse(readFileSync(`${d}/${t}.json`)),S=R('resumo');
const ps=R('pedidos'),items=R('pedido_itens'),as=R('anuncios'),dp=R('anuncio_desempenho_diario'),vs=R('vendas_diarias'),form=R('formula_base_precos'),ads=R('anuncio_ads');
const sum=(a,k)=>a.reduce((s,r)=>s+Number(r[k]??0),0),round=n=>Math.round(n*100)/100,chg=(a,b)=>a?round((b/a-1)*100):null;
const group=(a,f)=>{const m=new Map;for(const x of a){const k=f(x);if(!m.has(k))m.set(k,[]);m.get(k).push(x)}return m};
const amap=new Map(as.map(x=>[x.id,x])),codes=new Map(as.map(x=>[x.codigo_externo,x])),pm=new Map(ps.map(x=>[x.id,x]));
const main=S.accounts.find(a=>a.name.includes('São Paulo')),second=S.accounts.find(a=>a.name.includes('2ª conta')),vtex=S.accounts.find(a=>a.name.includes('VTEX'));
const sp=S.productAccounts.filter(x=>x.account.includes('São Paulo'));
const out={};
out.decomposition={};for(const [label,p1,p2]of[['jul_ago','jul','ago'],['ago_set20','ago20','set20'],['weekly','w3','w4'],['fortnight','prev14','last14']]){const a=main.periods[p1],b=main.periods[p2],na=a.orders-a.cancel,nb=b.orders-b.cancel,va=a.diarias.visits,vb=b.diarias.visits;const ta=a.net/na,tb=b.net/nb;out.decomposition[label]={before:a,after:b,delta:round(b.net-a.net),pct:chg(a.net,b.net),orderPct:chg(na,nb),ticketPct:chg(ta,tb),visitPct:chg(va,vb),conversionBefore:round(na/va*100),conversionAfter:round(nb/vb*100),trafficEffect:round((vb-va)*(na/va)*ta),conversionEffect:round(vb*((nb/vb)-(na/va))*ta),ticketEffect:round(nb*(tb-ta))};}
out.itemReconciliation=[];for(const acc of[main,second,vtex])for(const [label,start,end]of[['jul','2026-07-01','2026-07-31'],['ago','2026-08-01','2026-08-31'],['set20','2026-09-01','2026-09-20']]){const pp=ps.filter(p=>p.conta_canal_id===acc.id&&!p.cancelado&&p.data>=start&&p.data<=end);const ids=new Set(pp.map(p=>p.id)),ii=items.filter(i=>ids.has(i.pedido_id));const sums=group(ii,i=>i.pedido_id);out.itemReconciliation.push({acc:acc.name,period:label,orderTotal:round(sum(pp,'total')),itemTotal:round(sum(ii,'total')),orders:pp.length,withItems:sums.size,freteComprador:round(sum(pp,'frete')),unexplained:round(sum(pp,'total')-sum(ii,'total')-sum(pp,'frete'))});}
out.abc={};for(const per of['jul','ago','set20']){let rows=sp.filter(s=>s.periods[per].revenue>0).sort((a,b)=>b.periods[per].revenue-a.periods[per].revenue);let total=rows.reduce((s,r)=>s+r.periods[per].revenue,0),cum=0;out.abc[per]=rows.map(r=>{let prev=cum;cum+=r.periods[per].revenue;return{sku:r.sku,title:r.title,...r.periods[per],share:round(r.periods[per].revenue/total*100),cum:round(cum/total*100),abc:prev/total<.8?'A':prev/total<.95?'B':'C',allPaused:r.listings.length>0&&r.listings.every(l=>l.status==='pausado'),listings:r.listings.map(l=>({mlb:l.mlb,status:l.status,stock26ago:l.stock?.disponivel??null}))}})}
out.paused={};for(const per of['jul','ago','set20']){const rows=out.abc[per];out.paused[per]={total:round(sum(rows,'revenue')),pausedRevenue:round(sum(rows.filter(r=>r.allPaused),'revenue')),pausedSkus:rows.filter(r=>r.allPaused).length,top10Paused:rows.slice(0,10).filter(r=>r.allPaused).map(r=>r.sku),curveAPaused:rows.filter(r=>r.abc==='A'&&r.allPaused).map(r=>r.sku)}}
out.cancellations=[];for(const acc of[main,second,vtex])for(const month of['2026-08','2026-09']){const pp=ps.filter(p=>p.conta_canal_id===acc.id&&p.data.startsWith(month));const cc=pp.filter(p=>p.cancelado);out.cancellations.push({account:acc.name,month,orders:pp.length,canceled:cc.length,zeroCanceled:cc.filter(p=>p.total===0).length,cancelValue:round(sum(cc,'total')),days:[...group(cc,p=>p.data)].map(([date,aa])=>({date,count:aa.length,zero:aa.filter(p=>p.total===0).length,value:round(sum(aa,'total'))})).sort((a,b)=>b.count-a.count).slice(0,6),status:[...group(pp,p=>p.status)].map(([status,a])=>({status,n:a.length,value:round(sum(a,'total'))}))})}
out.adsCampaign=[...group(ads,a=>a.inicio+'|'+a.fim+'|'+a.campanha)].map(([k,a])=>({key:k,spend:round(sum(a,'investimento')),revenue:round(sum(a,'receita')),clicks:sum(a,'cliques'),direct:sum(a,'vendas_diretas'),indirect:sum(a,'vendas_indiretas')})).filter(a=>a.spend>0).sort((a,b)=>b.spend-a.spend);
out.adsListings=ads.filter(a=>a.inicio==='2026-08-01'&&a.investimento>0).map(a=>({...a,sku:amap.get(a.anuncio_id)?.sku_canal,currentStatus:amap.get(a.anuncio_id)?.status,acos:a.receita>0?round(a.investimento/a.receita*100):null})).sort((a,b)=>b.investimento-a.investimento);
out.priceSameSku=sp.filter(r=>r.periods.jul.units>=5&&r.periods.ago.units>=2).map(r=>({sku:r.sku,jul:r.periods.jul,ago:r.periods.ago,priceChange:chg(r.periods.jul.asp,r.periods.ago.asp),unitChange:chg(r.periods.jul.units,r.periods.ago.units)}));
const setitems=items.filter(i=>{const p=pm.get(i.pedido_id);return p&&!p.cancelado&&p.data>='2026-09-01'&&p.data<='2026-09-20'&&p.conta_canal_id===main.id});
out.formula=[];for(const i of setitems){const p=pm.get(i.pedido_id),a=amap.get(i.anuncio_id)||codes.get(i.codigo_externo);const valid=form.filter(f=>f.vigente_de<=p.data&&((f.chave_tipo==='mlb'&&f.chave===i.codigo_externo)||(f.chave_tipo==='sku'&&f.chave===(i.sku||a?.sku_canal))));const mlb=valid.filter(f=>f.chave_tipo==='mlb'),ff=mlb.length?mlb:valid;const date=ff.map(f=>f.vigente_de).sort().at(-1);const latest=ff.filter(f=>f.vigente_de===date),floor=latest.length?Math.min(...latest.map(f=>f.preco)):null;out.formula.push({sku:i.sku||a?.sku_canal,mlb:i.codigo_externo,date:p.data,units:i.quantidade,unitPrice:i.preco_unitario,total:i.total,floor,below:floor!=null&&i.preco_unitario<floor,version:date});}
out.trafficDaily=[...group(dp,r=>(amap.get(r.anuncio_id)?.conta_canal_id||'unknown')+'|'+r.data)].map(([key,a])=>({key,rows:a.length,visits:sum(a,'visitas')}));
out.duplicates=[...group(ps,p=>p.conta_canal_id+'|'+p.codigo_externo)].filter(([k,a])=>a.length>1).length;
out.secondaryDuplicates=[...group(ps.filter(p=>p.codigo_secundario),p=>p.conta_canal_id+'|'+p.codigo_secundario)].filter(([k,a])=>a.length>1).map(([key,a])=>({key,rows:a.length,revenue:round(sum(a,'total'))}));
writeFileSync(`${d}/aprofundamento.json`,JSON.stringify(out,null,2));
console.log(JSON.stringify({decomposition:out.decomposition,itemReconciliation:out.itemReconciliation,paused:out.paused,cancellations:out.cancellations,adsCampaign:out.adsCampaign,formula:{all:out.formula.length,covered:out.formula.filter(x=>x.floor!=null).length,below:out.formula.filter(x=>x.below).length,belowRows:out.formula.filter(x=>x.below).slice(0,15)},duplicates:out.duplicates,secondaryDuplicates:out.secondaryDuplicates.slice(0,5)},null,2));
